version: "3.9"

services:
  nodejs-backend-challenge:
    build: .
    container_name: nodejs-backend-challenge
    image: nodejs-backend-challenge
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ${PWD}:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: bitnami/postgresql
    container_name: dbpostgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    